apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: gstore-channel
  namespace: gstore-channel-ns
  labels:
    app: gstore-application
spec:
  type: GitHub
  pathname: https://github.com/GandhiCloudLab/mcm-130-using-git.git