apiVersion: v1
kind: Namespace
metadata:
  name: gstore-hub-ns
  labels:
    app: gstore-application
---
apiVersion: v1
kind: Namespace
metadata:
  name: gstore-app-ns
  labels:
    app: gstore-application