apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: gstore-sales
  namespace: gstore-subscription-ns
  labels:
    app: gstore-application
spec:
  clusterReplicas: 1
  clusterLabels:
    matchExpressions:
      - key: cloud
        operator: In
        values:
        - IBM