apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: gstore-purchase
  namespace: gstore-subscription-ns
  labels:
    app: gstore-application
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      cloud: IBM