apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: gstore-sales-subscription
  namespace: gstore-hub-ns
  labels:
    main-app: gstore-application
spec:
  channel: gstore-hub-ns/gstore-channel
  # source: https://raw.githubusercontent.com/GandhiCloudLab/mcm-130-using-git/master/charts/tgz/
  # source: https://github.com/GandhiCloudLab/mcm-130-using-git/tree/master/charts/tgz
  name: gstore-sales
  packageFilter:
    version: 0.1.0
  placement:
    placementRef:
      name: gstore-sales
      kind: PlacementRule
      group: app.ibm.com
  # placement:
  #   local: false
    
