apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: gstore-purchase-subscription
  namespace: gstore-hub-ns
  labels:
    main-app: gstore-application
spec:
  channel: gstore-hub-ns/gstore-channel
  # source: https://raw.githubusercontent.com/GandhiCloudLab/mcm-130-using-git/master
  name: gstore-purchase
  packageFilter:
    version: 0.1.0
  placement:
    placementRef:
      name: gstore-purchase
      kind: PlacementRule
      group: app.ibm.com
  # placement:
  #   local: false